### ISSUE TITLE
Verify led file path

### ISSUE THREAD

**Issue by Top-Ranger** [sam-hobbs/harbour-hammerhead-torch#3]
It would be good if the led path could be 'verified' in some way to prevent writes to random files. Although I don't see a huge risk in this it would still be nice to fix.

My suggestion:
- The path should begin with '/sys/' as it is very unlikely that the led control file is outside of sys
- The path should contain 'flash' or 'led'

This should secure the path while still being flexible enough to allow other devices. If you agree with my idea I would be willing to implement it (most likely by using [QRegExp](http://doc.qt.io/qt-5/qregexp.html) ).

**Comment by sam-hobbs** [comment]
Sure, that sounds like a solid plan, I'd gratefully merge those changes.

We'll have to be careful with the 'flash'/'led' requirement because there's no guarantee that other ports will follow the same conventions - I'll see if I can determine the control file locations for other ports by downloading and extracting the SFOS zips. Thinking about it, it may be part of the underlying CM installation.

Something else in the back of my mind is that these changes may make it more difficult to test in the emulator - when I rewrote the detection routine I copied the Hammerhead /etc/hw-release file into the emulator for testing, but that wouldn't necessarily be obvious to someone doing it for the first time. And at present detectPath falls back on $HOME/harbour-hammerhead-torch.txt, which is useful because you can verify that the file has been written to in the emulator, but that would have to come out. Probably unavoidable.

Maybe we could set the default control file location to an empty string, in which case operations that write to it would fail when opening the file and do nothing.

What do you think?

**Comment by Top-Ranger** [comment]
I've pushed a first proposal at https://github.com/Top-Ranger/harbour-hammerhead-torch - maybe you want to have a look on it.

Right now it only checks for '/sys/' at the beginning of the path, although this should easily be extensible.

As for 'flash'/'led' - I think it is a trade-off between convenience of easily adding new devices and security of not writing in unwanted files - however by only allowing files in '/sys/' a lot is already gained. 

It should be easy to see when the path is considered invalid - it is both shown in the settings page and in the config file (by prepending 'INVALID - '). As for the '$HOME/harbour-hammerhead-torch.txt' test - I'm not sure what to do about it. I have to think about it a bit more. Maybe you have an idea in the mean time.

**Comment by sam-hobbs** [comment]
Hey, sorry I didn't get back to you. I checked your changes over the weekend and like them, I plan on merging them tonight. Still waiting for someone to tell me what the control file location is for the Jolla C before I package a new version.
